---
title: Cases in research ethics
author: Adam La Caze
date: August 2019
bibliography: files/local.bib
output:
    revealjs::revealjs_presentation:
        self_contained: false
        lib_dir: files
        css: files/myreveal.css
        theme: white
        transition: none
        slide_level: 2
        reveal_options:
            slideNumber: true
            center: false
    pdf_document:
        includes:
            in_header: ${HOME}/Dropbox/Pandoc/pandoc_DATADIR/templates/RMD_preamble.tex
        template: ${HOME}/Dropbox/Pandoc/pandoc_DATADIR/templates/RMD_latextemp.latex
        keep_tex: true
        citation_package: biblatex
---

## Objectives

1. Apply the knowledge you have developed regarding human research ethics
1. Further develop your understanding of research ethics through the discussion of a number of contentious cases
2. Further develop your ethical reasoning skills


## Principles of research ethics

* Research merit and integrity
* Respect autonomy
* Promote good outcomes (beneficence)
* Avoid harm (non-maleficence)
* Be fair (justice)


## National Statement: Elements of Research

1. Research scope, aims, themes, questions and methods
2. Recruitment
3. Consent
4. Collection, use and management of data and information
5. Communication of research findings or results to participants
6. Dissemination of research outputs and outcomes
7. After the project

<p class="question">Read this section of the [National Statement](https://www.nhmrc.gov.au/about-us/publications/national-statement-ethical-conduct-human-research-2007-updated-2018#toc__374)</p> 


## Phase I, first-in-humans trial {data-background=#51247A}

*Anothernib* is a new biologic drug is being trialled in chronic myeloid leukaemia.

The objectives of the trial are to determine the maximum tolerated dose and, hopefully, gain some data on the minimal effective dose.

The trial will enrol patients that have failed all other treatments and have poor prognosis (life expectancy measured in months).


<p class="questionalt fragment">Discuss the key ethical considerations involved in such a study</p> 

<div class="notes">
There are a lot of examples of trials like this.
For one example, see @Druker:2001tx.
</div>

## Key considerations {data-background=#00A2C7}


* Possibility of patient benefit is very small
* How do we ensure that patients make an informed decision to participate? 
* Participants need a clear understanding of:
    - Likely benefit
    - Alternatives
    - The burdens of participation

## Genetic testing {data-background=#fbb800}

A study seeks to assess a new drug for the treatment of skin cancer.

To participate in the trial, patients need to consent to genetic testing, including:

> * Testing for somatic mutations related to the tumour
> * Pharmacogenomic mutations related to the pharmacokinetics of the investigational drug
> * Genetic screening (including whole genome sequencing) for genes related to skin cancer

## Questions

* Should genetic testing be the price of entry into a study?
* What details regarding genetic testing need to be given to a participant so that they can make an informed decision?
* In what situations should investigators communicate the results of genetic testing to participants?

<div class="notes">
This is a changing area.

See [National Statement](https://www.nhmrc.gov.au/about-us/publications/national-statement-ethical-conduct-human-research-2007-updated-2018#toc__826) for discussion.

@Fabsitz2011 also provides discussion.
</div>

## Databank

A pharmaceutical company that makes a new drug used for a rare genetic spinal disease seeks to set up a databank.

The databank will recruit all patients taking the drug and collect information on their response, other drugs, and related outcomes.

The company also seeks to collect any left over blood or tissue for genetic tests.

All data will be retained by the company and will not be accessible to third parties.

<p class="question fragment">Discuss the pros and cons of this proposal</p> 


## Considerations

<p class="question">This is a good example in which it is important to achieve two things: transparency and security (NS 3.1.55--62)</p>

<p class = "fragment">Need to ensure that individual data cannot be re-identified</p>

<p class = "fragment">Need to ensure that the data provided by participants is available for use by the scientific community (for the benefit of patients)</p> 

<div class="notes">
There is a lot of information available about Open Science and the risks of identifying participants from data sharing.

Two examples include: [BMJ Open Data](https://www.bmj.com/open-data) and the [Office of the Australian Information Commissioner](https://www.oaic.gov.au/privacy/privacy-decisions/investigation-reports/mbspbs-data-publication/) on the re-identification of PBS data shared publicly.
</div>

## Who benefits?

<p class = "question">How should we assess a well-designed trial that is unlikely to benefit anyone other than the sponsor?</p>

> * Some me-too drugs provide limited public and individual patient benefit
> * Esomeprazole is the *active* S-enantiomer of omeprazole (esomeprazole 20mg is roughly equivalent to omeprazole 40mg)
> * Most trials compare esomeprazole 40mg with omeprazole 20mg or 40mg

## Industry bias

-   @Lundh2017 conducted a meta-analysis of reports of studies that
    assessed samples of papers for industry bias
-   Industry sponsored studies more often had favourable efficacy
    results (RR 1.27, 95% CI 1.17--1.37)
-   This effect is present despite industry sponsored studies possessing
    similar (or lower) risk of bias when compared to non-industry
    sponsored studies.

<div class="notes">
For most of the studies included in the review 'favourable efficacy
results' equated to statistical significance.

Some possible explanations for industry bias [@Lundh2017 19]:

-   Inferior comparators
-   More likely to use placebo control
-   Active comparators at inferior doses
-   Inappropriate administration of drugs (?)
-   Choice of less-clinically relevant primary outcomes
-   Event coding, selective reporting and publication

</div>


## References {#small}
